# Generated by Django 5.0.6 on 2024-12-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classnest_Base', '0002_profile_github_link_profile_linkedin_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='course_thumbnails/default-thumbnail.jpg', null=True, upload_to='course_thumbnails/'),
        ),
    ]
